import { IRequisition } from 'src/interfaces/requisitions-interfaces'

export const initRequisitions: IRequisition[] = [
  {
    idOferta: 4392,
    folioRequisicion: 3371,
    tipoVacante: 'Nueva',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'GERENTE DE CONTABILIDAD',
    lider: 'MORENO ESCARCEGA GUSTAVO ALBERTO',
    solicitante: 'MORENO ESCARCEGA GUSTAVO ALBERTO',
    fechaCreacion: '2024-08-08T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Contaduría Publica, Administración, Economía',
    programa: 'Microsoft Office: Excel, Word, Power Point',
    tienePersonal: 'Si',
    requiereViajar: 'No',
    frecuencia: 'No se requiere viajar',
    funcionesPrincipales:
      'Preparación, registro y control del Flujo de Caja\r\nAdministración y Control de las Ctas. Bancarias\r\nIdentificación, registro, administración y control de Contratos con Clientes y Proveedores\r\nPreparación y control de Presupuesto Financiero\r\nGeneración de controles que garanticen la gestión ordenada de las operaciones de las sociedades administradas\r\nIdentificación registro y control de las operaciones Intercompañías\r\nSupervisión y coordinación de la generación de información de Estos Financieros de empresas asociadas\r\nAdministración, seguimiento y control de los pasivos financieros \r\nGeneración de los Estados Financieros y principales cédulas analíticas, de forma mensual y anual relativas a los clientes, proveedores y acreedores\r\nAseguramiento de la aplicación de las Normas de Información Financiera adoptadas por la administración\r\n',
    tiempoExperiencia: '5 años',
    relacionAreas: 'Relación con áreas administrativas y financieras de empresas relacionadas',
    ebs: 'Si',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'Si',
    otrosAccesos: 'Microsoft Office: Excel, Word, Power Point',
  },
  {
    idOferta: 4474,
    folioRequisicion: 3450,
    tipoVacante: 'Nueva',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'GERENTE DE SINIESTROS DAÑOS',
    lider: 'ROMERO ARAIZAGA JUAN ALBERTO',
    solicitante: 'ROMERO ARAIZAGA JUAN ALBERTO',
    fechaCreacion: '2024-09-25T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Administración o a fin',
    programa: 'Office Avanzado',
    tienePersonal: 'Si',
    requiereViajar: 'Si',
    frecuencia: 'dos veces al mes',
    funcionesPrincipales:
      'Monitorear el proceso de trámite de siniestros para lograr el cumplimiento de los SLA´s establecidos\r\n\r\nSupervisar la calidad de la atención de los clientes externos e internos\r\n\r\nCoordinar y ejecutar la estrategia de servicio establecida para cada cliente\r\n\r\nReportar en las juntas de operación, el estatus del cumplimiento de los niveles de servicio y las incidencias que eventualmente provocan desviación en éstos (internos y externos)\r\n\r\nMantener reuniones periódicas con sus ejecutivos para fomentar la comunicación, seguimiento y solución de problemas',
    tiempoExperiencia: '5 años',
    relacionAreas: 'con todas las áreas de la empresa',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'Si',
    otros: 'No',
    otrosAccesos: '',
  },
  {
    idOferta: 4495,
    folioRequisicion: 3468,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'AUXILIAR INPLANT',
    lider: 'GARCIA TELLEZ LUIS ANGEL',
    solicitante: 'GARCIA TELLEZ LUIS ANGEL',
    fechaCreacion: '2024-10-10T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Económico Administrativo o afin',
    programa: 'OFFICE',
    tienePersonal: 'No',
    requiereViajar: 'No',
    frecuencia: 'N/A',
    funcionesPrincipales:
      '* Administrar plataforma para dar altas y bajas a pólizas\r\n* Asesorar al cliente ante dudas',
    tiempoExperiencia: 'Sin experiencia',
    relacionAreas: 'Todas',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'Si',
    otrosAccesos: 'Dynamics, Power BI',
  },
  {
    idOferta: 4587,
    folioRequisicion: 3559,
    tipoVacante: 'Nueva',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'SUBDIRECTOR SERVICIO AL CLIENTE Y HUNTING',
    lider: 'MARTINEZ LUENGO LUIS ESTEBAN',
    solicitante: 'MARTINEZ LUENGO LUIS ESTEBAN',
    fechaCreacion: '2025-01-06T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Administración o a fin',
    programa: 'Office Avanzado',
    tienePersonal: 'No',
    requiereViajar: 'Si',
    frecuencia: 'dos veces al mes',
    funcionesPrincipales:
      'colaborar en estrategias del negocio digital\r\nimplementar estretgias digitales\r\nnegociar con clientes para cerrar negocio\r\nimplementar programas\r\nestregias del area',
    tiempoExperiencia: '5 años',
    relacionAreas: 'CON TODAS LAS AREAS',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'No',
    otrosAccesos: '',
  },
  {
    idOferta: 4591,
    folioRequisicion: 3562,
    tipoVacante: 'Nueva',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'SUBDIRECTOR DE OPERACIONES REGIONAL',
    lider: 'SALDIERNA HINOJOSA MARIBEL',
    solicitante: 'SALDIERNA HINOJOSA MARIBEL',
    fechaCreacion: '2025-01-09T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Económico Administrativo o afin',
    programa: 'OFFICE',
    tienePersonal: 'Si',
    requiereViajar: 'Si',
    frecuencia: '1 o 2 veces al mes',
    funcionesPrincipales:
      'Definir y/o aprobar la estrategia de servicio de cada oficina regional; y medir el alcance los objetivos financieros y de servicio definidos por la Dirección General\r\nDiseñar e implementar la estrategia de renovación, las mejoras en la propuesta de valor, las oportunidades de venta cruzada, la recuperación de cuentas y soluciones disruptivas a los clientes, en conjunto con los responsables de Oficinas Regionales y con Técnico, por medio del análisis profundo de la composición de la cartera.\r\nDesarrollar y mantener relaciones efectivas de largo plazo con los clientes, socios de negocio, así como con los dueños de las cuentas\r\nImplementar y validar la correcta ejecución del modelo operativo en las oficinas regionales',
    tiempoExperiencia: '5 años de experiencia',
    relacionAreas: 'Todas',
    ebs: 'Si',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'Si',
    otros: 'Si',
    otrosAccesos: 'Power BI, Dynamics',
  },
  {
    idOferta: 4628,
    folioRequisicion: 3601,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'TECNICO AUTOS',
    lider: 'MIRANDA MARQUEZ ROSA MARIA',
    solicitante: 'MIRANDA MARQUEZ ROSA MARIA',
    fechaCreacion: '2025-01-23T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Actuaria, Económico, Administrativo o afín',
    programa: 'OFFICE',
    tienePersonal: 'No',
    requiereViajar: 'No',
    frecuencia: 'N/A',
    funcionesPrincipales:
      'Uso y control de las facilidades desarrolladas, cotizando los negocios en los tiempos establecidos\r\nRealizar el peer review complejos por su tamaño, estructura o riesgo (de acuerdo a lo definido en la política) del ramo del que es responsable\r\nApoyar a los otros miembros del equipo en la negociación de las cuentas del ramo del que es espec\r\nTecnico Autos',
    tiempoExperiencia: 'Mínimo 3 años',
    relacionAreas: 'Servicio, Siniestros, Aseguradoras, Clientes',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'Si',
    bi: 'No',
    otros: 'Si',
    otrosAccesos: 'Power BI, Dynamics',
  },
  {
    idOferta: 4641,
    folioRequisicion: 3613,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'EJECUTIVO DE SERVICIO SR',
    lider: 'PERALTA OLIVERA LAZARO',
    solicitante: 'PERALTA OLIVERA LAZARO',
    fechaCreacion: '2025-01-31T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Económico Administrativo o afin',
    programa: 'OFFICE',
    tienePersonal: 'No',
    requiereViajar: 'Si',
    frecuencia: '1 o 2 veces al mes',
    funcionesPrincipales:
      'Proteger la confidencialidad, integridad y disponibilidad de toda la información a la que tenga acceso, siguiendo las políticas y procedimientos; reportando incidentes o actividades sospechosas y participando en las actividades de difusión en materia de seguridad de la información\r\nAsesorar y actualizar al cliente de manera oportuna en la administración y renovación de sus pólizas, generación de OTs , movimientos al día (altas, bajas, seguimiento a endosos, seguimiento de solicitudes)\r\nBuscar el crecimiento de cartera de manera orgánica y por venta cruzada\r\nCrear y mantener relaciones con los clientes al más alto nivel',
    tiempoExperiencia: '3 años',
    relacionAreas: 'Todas',
    ebs: 'Si',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'Si',
    otros: 'Si',
    otrosAccesos: 'Power BI, Dynamics',
  },
  {
    idOferta: 4647,
    folioRequisicion: 3619,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'REPRESENTANTE DE VENTAS TIEMPO PARCIAL',
    lider: 'EMIGDIO GARNICA CARLOS',
    solicitante: 'EMIGDIO GARNICA CARLOS',
    fechaCreacion: '2025-02-05T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'PREPARATORIA',
    especialidad: 'N/A',
    programa: 'Paquetería Office',
    tienePersonal: 'No',
    requiereViajar: 'No',
    frecuencia: 'N/A',
    funcionesPrincipales:
      'Venta con registros de lead, cobro de la venta, atención, llenado de bases en excel sobre sus ventas y whatsapp web',
    tiempoExperiencia: '6 meses en ventas o atc',
    relacionAreas: 'Si, con todas',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'Si',
    otrosAccesos:
      'Correo electrónico, CIO, CRM QUATTRO, Copsis, y no es necesario laptop ya que ocupan equipo de computo de escritorio\r\n\r\nNOTA: No requiere laptop',
  },
  {
    idOferta: 4650,
    folioRequisicion: 3622,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'EJECUTIVO DE REASEGURO SR',
    lider: 'DEL ROSAL BALCAZAR EDUARDO EDMUNDO',
    solicitante: 'DEL ROSAL BALCAZAR EDUARDO EDMUNDO',
    fechaCreacion: '2025-02-06T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Actuaria, Económico, Administrativo o afín',
    programa: 'OFFICE',
    tienePersonal: 'No',
    requiereViajar: 'Si',
    frecuencia: '1 o 2 veces al año',
    funcionesPrincipales:
      '* Generación de propuestas de reaseguro a clientes \r\n* Cotización con mercados locales y Londres de negocios de reaseguro\r\n* Elaboración de endosos, términos y condiciones de las propuestas de reaseguro\r\n* Negociación con clientes y reaseguradores\r\n* Cumplimiento del proceso (compliance)',
    tiempoExperiencia: '3 años',
    relacionAreas: 'Todas, Aseguradoras, Reaseguradores',
    ebs: 'No',
    inbrokerRe: 'Si',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'No',
    otrosAccesos: '',
  },
  {
    idOferta: 4653,
    folioRequisicion: 3625,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'GERENTE DE SERVICIO ENERGY',
    lider: 'HERNANDEZ CASTILLO JAVIER',
    solicitante: 'HERNANDEZ CASTILLO JAVIER',
    fechaCreacion: '2025-02-11T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Económico Administrativo o afin',
    programa: 'OFFICE',
    tienePersonal: 'Si',
    requiereViajar: 'Si',
    frecuencia: '1 o 2 veces al año',
    funcionesPrincipales:
      'Dirigir e implementar la estrategia de servicio establecida para cada Cliente\r\nSupervisar la atención al cliente, a través de la coordinación y comunicación con las áreas de Reaseguro, Técnico, Siniestros, Comercial, Cobranza CES; Internacional para la solución oportuna de las necesidades de los Clientes\r\nDirigir el mantenimiento de la cartera, asesoría en planes de capacitación para el Cliente y el Área\r\nConocimiento de los productos y servicios que ofrece el Grupo, (industria y particularidades del cliente)\r\nProporcionar asesoría y consultoría al cliente para crear una propuesta de valor y de manera integral considerando los riesgos actuales y previéndolos en empresas del sector de ENERGIA',
    tiempoExperiencia: '5 años de experiencia',
    relacionAreas: 'TODAS',
    ebs: 'Si',
    inbrokerRe: 'Si',
    inbrokerSofia: 'No',
    bi: 'Si',
    otros: 'Si',
    otrosAccesos: 'POWER BI DYNAMICS',
  },
  {
    idOferta: 4671,
    folioRequisicion: 3643,
    tipoVacante: 'Nueva',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'OFFICE COORDINATOR',
    lider: 'FERNANDEZ DELGADO MARIA ELENA',
    solicitante: 'FERNANDEZ DELGADO MARIA ELENA',
    fechaCreacion: '2025-02-26T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Administración o a fin',
    programa: 'Office Avanzado',
    tienePersonal: 'No',
    requiereViajar: 'Si',
    frecuencia: 'dos veces al mes',
    funcionesPrincipales:
      'Implementar controles internos para salvaguardar los activos fijos, así como de realizar inventarios físicos una vez al año y reportar los resultados al contador de activos fijos del corporativo\r\n\r\nGestionar y validar la relación con proveedores locales para contratación & facturación de bienes y servicios relacionados con la oficina en coordinación con las áreas de TI y servicios Generales del Corporativo\r\n\r\nRevisar la información Financiera Mensual que reporta el Despacho contable y Fiscal para estar actualizado sobre la situación financiera de la oficina y poder realizar los reportes a la unidad de negocio correspondiente\r\n\r\nValidar el cumplimiento normativo del Agente de Seguros junto con Legal Corporativo para garantizar que la compañía esté en orden en cuanto a los lineamientos normativos, así como del cumplimiento de temas relacionados con protección civil',
    tiempoExperiencia: '3',
    relacionAreas: 'con todas de la empresa',
    ebs: 'Si',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'Si',
    otros: 'No',
    otrosAccesos: '',
  },
  {
    idOferta: 5673,
    folioRequisicion: 3649,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'KAM',
    lider: 'GONZALEZ RENOVATO MARIA DEL CARMEN',
    solicitante: 'GONZALEZ RENOVATO MARIA DEL CARMEN',
    fechaCreacion: '2025-02-28T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Económico Administrativo o afin',
    programa: 'OFFICE',
    tienePersonal: 'No',
    requiereViajar: 'Si',
    frecuencia: '1 o 2 veces al año',
    funcionesPrincipales:
      'Implementar la estrategia de venta nueva y cruzada definida por la Desarrollo de Negocio y Coordinación de Foráneas\r\nIncrementar la cartera a través de venta nueva y cruzada coordinando la colocación de los negocios con las diferentes áreas\r\nDesarrollar, elaborar y entregar en tiempo los concursos para propuestas de seguros y fianzas asegurando que cumpla con las necesidades del cliente\r\nCumplir con los objetivos definidos por el área',
    tiempoExperiencia: '3 años',
    relacionAreas: 'Todas',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'Si',
    otros: 'Si',
    otrosAccesos: 'Power BI, Dynamics',
  },
  {
    idOferta: 5684,
    folioRequisicion: 3660,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'CONTADOR JR - AP',
    lider: 'PATRACA CRUZ OSIRIS CRISTINA',
    solicitante: 'PATRACA CRUZ OSIRIS CRISTINA',
    fechaCreacion: '2025-03-05T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Administrativo economico o afin',
    programa: 'Office',
    tienePersonal: 'No',
    requiereViajar: 'No',
    frecuencia: 'NA',
    funcionesPrincipales:
      'Recibir, revisar y registrar las cuentas por pagar de proveedores, acreedores, anticipos y provisiones de todas las empresas de Grupo INTER (incluyendo actividades de intermediación de Reaseguro y operaciones intercompañía)\r\n[Editar] [Quitar]\r\nHacer el correcto registro de las transacciones de pasivos y pagos conforme a IFRS , criterios de UBN y Centro de Costos y legislación fiscal aplicable\r\n\r\nRealizar los registros contables de las cuentas por pagar conforme a lo establecido en contratos, actas de asamblea y documentos legales queden reflejados en contabilidad en tiempo y forma\r\n\r\nRegistrar, revisar, procesar y monitorear la comprobación de anticipos y reembolso de gastos de los colaboradores relacionados a la operación del negocio',
    tiempoExperiencia: '6 meses, 1 año o 2 años',
    relacionAreas: 'Compras, tesoreria, capital humano',
    ebs: 'Si',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'No',
    otrosAccesos: '',
  },
  {
    idOferta: 5710,
    folioRequisicion: 3685,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'EJECUTIVO DE SERVICIO SR',
    lider: 'FUENTES MAYORAL DIANA',
    solicitante: 'FUENTES MAYORAL DIANA',
    fechaCreacion: '2025-03-19T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Económico Administrativo o afin',
    programa: 'OFFICE',
    tienePersonal: 'No',
    requiereViajar: 'Si',
    frecuencia: '1 o 2 veces al año',
    funcionesPrincipales:
      'Asesorar y actualizar al cliente de manera oportuna en la administración y renovación de sus pólizas, generación de OTs , movimientos al día (altas, bajas, seguimiento a endosos, seguimiento de solicitudes)\r\nBuscar el crecimiento de cartera de manera orgánica y por venta cruzada\r\nCrear y mantener relaciones con los clientes al más alto nivel\r\nAsegurar la atención al cliente mediante la coordinación y comunicación con las áreas de siniestros, técnico, cobranza, estadísticas y CES para la solución oportuna de sus necesidades\r\nProveer soluciones disruptivas al cliente considerando el alcance de los servicios de INTER, socios y alianzas mediante el conocimiento de sus productos y servicios.',
    tiempoExperiencia: '3 años',
    relacionAreas: 'Todas',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'Si',
    otros: 'Si',
    otrosAccesos: 'Power BI, Dynamics',
  },
  {
    idOferta: 5711,
    folioRequisicion: 3686,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'EJECUTIVO DE SERVICIO JR ELITE',
    lider: 'HERRERA BELTRAN VICTOR DANIEL',
    solicitante: 'HERRERA BELTRAN VICTOR DANIEL',
    fechaCreacion: '2025-03-21T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Administrativo economico, Contaduria o afin',
    programa: 'Office',
    tienePersonal: 'No',
    requiereViajar: 'Si',
    frecuencia: 'Cada 6 meses',
    funcionesPrincipales:
      'Asesorar al cliente sobre términos y condiciones de la póliza y actualizar de manera oportuna en la administración de riesgos en todo momento\r\n\r\nMejorar la rentabilidad y crecer la cartera de manera orgánica y por venta cruzada\r\n\r\nCrear y mantener relaciones con los clientes al más alto nivel\r\n\r\nProveer soluciones disruptivas al cliente considerando el alcance de los servicios de INTER, socios y alianzas mediante el conocimiento de sus productos y servicios',
    tiempoExperiencia: '1 año',
    relacionAreas: 'Articulo 492, Siniestros, CES, Cobranza, Segmento de Patrimonios',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'Si',
    otrosAccesos: 'Dynamics',
  },
  {
    idOferta: 5712,
    folioRequisicion: 3689,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'EJECUTIVO DE REASEGURO JR',
    lider: 'MARTINEZ RIVERA ALEJANDRO ANTONIO',
    solicitante: 'MARTINEZ RIVERA ALEJANDRO ANTONIO',
    fechaCreacion: '2025-03-21T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad:
      'Economico, administrativos, actuaria, Ingenieria, Negocios internacionales, o afin',
    programa: 'Office',
    tienePersonal: 'No',
    requiereViajar: 'No',
    frecuencia: 'NA',
    funcionesPrincipales:
      'Elaboración de slips de cotización, confirmación\t\r\nElaboración de cuadros de primas\t\r\nTraducción y revisión de textos en Ingles/Español\r\nNegociación con mercados de reaseguro',
    tiempoExperiencia: 'Recien egresados (sin experiencia)',
    relacionAreas: 'Cobranza, Siniestros, QA, Servicio al cliente',
    ebs: 'No',
    inbrokerRe: 'Si',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'No',
    otrosAccesos: '',
  },
  {
    idOferta: 5717,
    folioRequisicion: 3691,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'EJECUTIVO QA STAFF',
    lider: 'MOSCO PALACIOS MARIA DEL CARMEN',
    solicitante: 'MOSCO PALACIOS MARIA DEL CARMEN',
    fechaCreacion: '2025-03-25T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Administrativo economico o afin',
    programa: 'Office',
    tienePersonal: 'No',
    requiereViajar: 'No',
    frecuencia: 'NA',
    funcionesPrincipales:
      'Revisión de documentos soporte de la transferencia de riesgo\r\n\r\nApoyo en la gestión para que la operación cumpla con lo solicitado por la CNSF y otras autoridades\r\n\r\nAsegurar el cumplimiento de las políticas de colocación\r\n\r\nDesarrollar y/o incorporar expertise técnico y normativo',
    tiempoExperiencia: 'Recien egresados (conocimientos basicos en seguro)',
    relacionAreas: 'Producción, Mesa de control, Siniestros',
    ebs: 'No',
    inbrokerRe: 'Si',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'No',
    otrosAccesos: '',
  },
  {
    idOferta: 5719,
    folioRequisicion: 3693,
    tipoVacante: 'Nueva',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'ESPECIALISTA JURIDICO B',
    lider: 'RODRIGUEZ CUERVO RODOLFO',
    solicitante: 'RODRIGUEZ CUERVO RODOLFO',
    fechaCreacion: '2025-03-26T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Derecho',
    programa: 'OFFICE',
    tienePersonal: 'No',
    requiereViajar: 'Si',
    frecuencia: '2 a 3 veces por semana',
    funcionesPrincipales: 'Civil, administrativa, penal, Servidores Públicos.',
    tiempoExperiencia: '1 o 2 años',
    relacionAreas: 'Proveedores externos en el ámbito médico legal',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'No',
    otrosAccesos: '',
  },
  {
    idOferta: 5722,
    folioRequisicion: 3695,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'DIRECTOR COMERCIAL',
    lider: 'PADRIZA CONTRERAS MONICA',
    solicitante: 'PADRIZA CONTRERAS MONICA',
    fechaCreacion: '2025-03-28T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Actuaria, Económico, Administrativo o afín',
    programa: 'OFFICE',
    tienePersonal: 'Si',
    requiereViajar: 'Si',
    frecuencia: '2 a 3 veces por semana',
    funcionesPrincipales:
      'Analizar y entender la información del mercado interno y externo para elaborar estrategia de venta del Grupo\t\r\nDesarrollar en conjunto con las Direcciones de Foráneas, TPA, Reaseguro, Técnico y Administración de Cuentas la estrategia de venta nueva, cruzada y recuperación de cuentas del Grupo\r\nImplementar la estrategia de venta nueva, cruzada y recuperación de cuentas del Grupo\r\nAcompañar a los dueños de cuenta en las labores de prospección de las cuentas que así lo requieran\r\nParticipar en el plan de visitas acordado con cada cliente de acuerdo a segmentación',
    tiempoExperiencia: '5 años de experiencia',
    relacionAreas: 'Todas',
    ebs: 'Si',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'Si',
    otros: 'Si',
    otrosAccesos: 'Power BI, Dynamics',
  },
  {
    idOferta: 5729,
    folioRequisicion: 3702,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'EJECUTIVO DE COBRANZA JR',
    lider: 'DE LA TORRE CERON IRVING ERIK',
    solicitante: 'DE LA TORRE CERON IRVING ERIK',
    fechaCreacion: '2025-04-01T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Administrativo economico o afin',
    programa: 'Office basico',
    tienePersonal: 'No',
    requiereViajar: 'No',
    frecuencia: 'NA',
    funcionesPrincipales:
      'Gestión de Cobranza con servicio al cliente\r\nAsegurar la aplicación del comprobante de pago correspondiente mediante el envío de avisos de cobro y el seguimiento por correo con el área de servicio al cliente (SAC)\t\r\nSolucionar casos específicos de cobranza mediante la interacción con las aseguradoras\t[Editar] [Quitar]\r\nNotificar a Servicio a Cliente sobre incidencias de cobro (cancelaciones a solicitud del cliente, depuración de saldos) y solicitudes de envío de documentos por parte del cliente.',
    tiempoExperiencia: '6 meses (Deseable)',
    relacionAreas: 'Servicio al cliente, Call Center, CES',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'No',
    otrosAccesos: '',
  },
  {
    idOferta: 5731,
    folioRequisicion: 3703,
    tipoVacante: 'Nueva',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'OFFICE COORDINATOR',
    lider: 'FERNANDEZ DELGADO MARIA ELENA',
    solicitante: 'FERNANDEZ DELGADO MARIA ELENA',
    fechaCreacion: '2025-04-01T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Administración o a fin',
    programa: 'Office Avanzado',
    tienePersonal: 'No',
    requiereViajar: 'Si',
    frecuencia: 'N/A',
    funcionesPrincipales:
      'Implementar controles internos para salvaguardar los activos fijos, así como de realizar inventarios físicos una vez al año y reportar los resultados al contador de activos fijos del corporativo\r\nGestionar y validar la relación con proveedores locales para contratación & facturación de bienes y servicios relacionados con la oficina en coordinación con las áreas de TI y servicios Generales del Corporativo\r\nRevisar la información Financiera Mensual que reporta el Despacho contable y Fiscal para estar actualizado sobre la situación financiera de la oficina y poder realizar los reportes a la unidad de negocio correspondiente\r\nValidar el cumplimiento normativo del Agente de Seguros junto con Legal Corporativo para garantizar que la compañía esté en orden en cuanto a los lineamientos normativos, así como del cumplimiento de temas relacionados con protección civil\r\nContribuir con el Despacho Fiscal en el monitoreo de las obligaciones fiscales, así como con la información que requieran para aclarar en tiempo y forma los temas administrativos que solicite dicho despacho\r\nResponsable de la gestión de estados de cuenta de aseguradoras y afianzadoras locales para detonar el proceso de facturación, así como de supervisar la emisión de la facturación para garantizar el correcto reconocimiento del ingreso de la compañía\r\nRegistrar y dar seguimiento a la producción de las pólizas generadas por la oficina para el reconocimiento de las comisiones ganadas y los ingresos, así como de supervisar la cobranza y aplicación contable para garantizar que las comisiones sean reconocidas y pagadas a la compañía\r\nEnviar la integración de ingresos mensual al corporativo para poder subir el ingreso a los monitores de BI\r\nAutorizar como representante legal los estudios médicos de altas y bajas de colaboradores, así como cualquier otro tramite que se requiera en el ámbito laboral por instrucciones de Capital Humano Corporativo',
    tiempoExperiencia: '3 años',
    relacionAreas: 'Con todas',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'Si',
    otros: 'No',
    otrosAccesos: '',
  },
  {
    idOferta: 5739,
    folioRequisicion: 3711,
    tipoVacante: 'Nueva',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'EJECUTIVO SR INTERNACIONAL',
    lider: 'PADRIZA CONTRERAS MONICA',
    solicitante: 'PADRIZA CONTRERAS MONICA',
    fechaCreacion: '2025-04-03T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Económico Administrativo o afin',
    programa: 'OFFICE',
    tienePersonal: 'No',
    requiereViajar: 'No',
    frecuencia: 'N/A',
    funcionesPrincipales:
      'Implementar la estrategia de venta nueva y cruzada definida por la Desarrollo de Negocio y Coordinación de Foráneas\r\nIncrementar la cartera a través de venta nueva y cruzada coordinando la colocación de los negocios con las diferentes áreas\r\nDesarrollar, elaborar y entregar en tiempo los concursos para propuestas de seguros y fianzas asegurando que cumpla con las necesidades del cliente\r\nCumplir con los objetivos definidos por el área',
    tiempoExperiencia: '3 años',
    relacionAreas: 'Todas',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'Si',
    otrosAccesos: 'Power BI, Dynamics',
  },
  {
    idOferta: 5743,
    folioRequisicion: 3714,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'EJECUTIVO DE SERVICIO SR ELITE',
    lider: 'GARCIA MARQUEZ ROBERTO',
    solicitante: 'GARCIA MARQUEZ ROBERTO',
    fechaCreacion: '2025-04-07T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'LICENCIATURA',
    especialidad: 'Económico Administrativo o afin',
    programa: 'OFFICE',
    tienePersonal: 'No',
    requiereViajar: 'No',
    frecuencia: 'N/A',
    funcionesPrincipales:
      'Asesorar al cliente sobre términos y condiciones de la póliza y actualizar de manera oportuna en la administración de riesgos en todo momento\r\nMejorar la rentabilidad y crecer la cartera de manera orgánica y por venta cruzada\r\nCrear y mantener relaciones con los clientes al más alto nivel\r\nProveer soluciones disruptivas al cliente considerando el alcance de los servicios de INTER, socios y alianzas mediante el conocimiento de sus productos y servicios',
    tiempoExperiencia: '3 años',
    relacionAreas: 'Todas',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'Si',
    otrosAccesos: 'Power BI, Dynamics',
  },
  {
    idOferta: 5752,
    folioRequisicion: 3724,
    tipoVacante: 'Reemplazo',
    tipoContratacion: 'INDETERMINADO',
    estado: 'Abierta',
    puestoACubrir: 'MONITOR DE CALIDAD',
    lider: 'VELEZ JUAREZ MARTHA ROSA',
    solicitante: 'VELEZ JUAREZ MARTHA ROSA',
    fechaCreacion: '2025-04-11T00:00:00',
    fechaCierre: '0001-01-01T00:00:00',
    escolaridad: 'PREPARATORIA',
    especialidad: 'N/A',
    programa: 'Paquetería Office',
    tienePersonal: 'No',
    requiereViajar: 'No',
    frecuencia: 'N/A',
    funcionesPrincipales:
      'Monitorear el cumplimiento de los procesos, protocolos e indicadores definidos por el negocio y responsable de las campañas para garantizar su servicio y sus objetivos. Desarrollar en conjunto con el Supervisor de calidad la estrategia de Calidad y Mejora Continua, revisar el cumplimiento de los procesos y parámetros definidos en cada línea de negocio. Dar seguimiento a la implementación de mejoras acordadas y definidas por todas las áreas y proveer a los responsables de las campañas de insights relevantes referente al servicio para poder llevar a cabo toma de decisiones estratégicas. Actualizar en conjunto con el Supervisor de calidad los documentos de gestión y operación de las diferentes campañas entre los que se encuentran los diagramas de proceso, los scripts, las matrices de documentación y la matriz de procesos. Elaborar y presentar de forma periódica los hallazgos obtenidos en las auditorías realizadas, así como el plan de acción a implementar. Brindar coaching al equipo para el logro de objetivos a un corto plazo a través de la medición de la desviación absoluta del error. Realizar auditorías a los canales de atención, para llegar a los kpis de forma cuantitativa y cualitativa. Retroalimentar a los asesores para desarrollar sus competencias, habilidades blandas y fuertes, así como la interpretación de estas para cumplir con las políticas de seguridad de la información establecidas. Por último, ejecutar calibraciones periódicas con todas las áreas involucradas en el negocio para cerrar acuerdos y seguimiento de estos.',
    tiempoExperiencia: '1 año',
    relacionAreas: 'Si, con todas las áreas dentro del call center',
    ebs: 'No',
    inbrokerRe: 'No',
    inbrokerSofia: 'No',
    bi: 'No',
    otros: 'Si',
    otrosAccesos:
      'Laptop, celular, correo electrónico, CIO, Inconcert, Quattro, Dynamics y paquetería office',
  },
]
